### ISSUE TITLE
ShowStack does not work

### ISSUE THREAD

**Issue by CThuleHansen** [jbblanchet/jasmine-terminal-reporter#3]
When I enable includeStackTrace it just prints F, so my tests will look like this:

Testname FailedF

I do not get the stacktrace.

**Comment by jbblanchet** [comment]
Could I get more details on your setup (node version, are you using the reporter directly or through gulp-jasmine, code you use to run your tests, etc).

For me, both these setup work:

_via gulp-jasmine_
```javascript
var gulp = require("gulp");
var jasmine = require("gulp-jasmine");

gulp.task("default", function () {
	gulp.src("test.spec.js")
		.pipe(jasmine({
			includeStackTrace: true
		}));
});
```

_or directly_
```javascript
var gulp = require("gulp");
var jasmine = require("gulp-jasmine");
var Reporter = require("jasmine-terminal-reporter");

gulp.task("default", function () {
	gulp.src("test.spec.js")
		.pipe(jasmine({
			reporter: new Reporter({ includeStackTrace: true })
		}));
});
```

**Comment by CThuleHansen** [comment]
I am using node + grunt, and I added the reporter by 
```
var Reporter = require("jasmine-terminal-reporter");
jasmine.getenv().addReporters(new Reporter({includeStackTrade: true}))}
```
I only work on Tuesdays, so I cannot supply any more info until next Tuesday.

**Comment by jbblanchet** [comment]
Not sure if it's a type here or in your original code, but you wrote includeStackTrade

**Comment by CThuleHansen** [comment]
Typo here, sorry. I will write more info on Tuesday, when I am back at work :)

**Comment by jbblanchet** [comment]
Hi,

Is this still an issue? I'm not sure if it was only a typo or not. If it still is an issue, I'd like to be able to reproduce it, but I'm not really familiar with grunt, and it looks as if grunt-contrib-jasmine has no way to add a custom reporter. If you could you give me a simplified gruntfile repoduces the error, I could look into it quickly. Thanks.

**Comment by CThuleHansen** [comment]
Hi jbblancet, sorry for not getting back to you.
I am no longer eomployed at the company, where the code is.
So I'll close this.
