### ISSUE TITLE
formatStack docs/code mismatch

### ISSUE THREAD

**Issue by amavisca** [jbblanchet/jasmine-terminal-reporter#7]
The docs refer to `formatStack` as the option to provide the custom stack function, but I think there's a mismatch between the docs and the code.

The formatter is handed the option without modifying it:
https://github.com/jbblanchet/jasmine-terminal-reporter/blob/master/index.js#L26

The formatter then sets its own property of formatStack, but was expecting it to be passed in as stackFilter. 
`this.formatStack = options.stackFilter || defaultStackFilter;`
https://github.com/jbblanchet/jasmine-terminal-reporter/blob/master/formatter.js#L25

Didn't send a PR since I'm not sure if this is a documentation issue or a code issue.

Thanks!

**Comment by jbblanchet** [comment]
formatStack is the internal function name. Thank you for reporting this issue.
