### ISSUE TITLE
Perhaps give an example of usage?

### ISSUE THREAD

**Issue by jyoungqu** [jbblanchet/jasmine-terminal-reporter#9]
Adding:
`var Reporter = require('jasmine-terminal-reporter');`
`var reporter = new Reporter(options)`

to specs does not produce any different output when "isVerbose:true" is passed in options.  Perhaps an actual example of spec with the reporter in use would make noobs like me understand how to actually use this.

**Comment by jbblanchet** [comment]
Hi!

Thanks for your comment. The problem here is that I don't know how to register the reporter to every spec runner there is. What are you using to run your tests?

**Comment by jyoungqu** [comment]
Running vanilla jasmine...
So specs are in a "spec" folder and in there is the "support" folder with the jasmine.json config.  Below is an example of what I have, just basic Describe and it()'s

example-spec.js:
```
var Reporter = require('jasmine-terminal-reporter');

describe("pretty tests", function() {
  var reporter = new Reporter({isVerbose: true});
  it("should be verbose in test results", function() {
    expect(1).toEqual(1);
  });
});
```

Jasmine.json file is pretty vanilla as well:
```
    {
        "spec_dir": "spec",
        "spec_files": [
            "**/*[sS]pec.js"
        ],
        "helpers": [
            "helpers/**/*.js"
        ],
       "stopSpecOnExpectationFailure": false,
       "random": false
    }
```

**Comment by jbblanchet** [comment]
From the [documentation](http://jasmine.github.io/2.4/custom_reporter.html) of jasmine:

```javascript
jasmine.getEnv().addReporter(myReporter);

describe('Top Level suite', function() {
  it('spec', function() {
    expect(1).toBe(1);
  });

  describe('Nested suite', function() {
    it('nested spec', function() {
      expect(true).toBe(true);
    });
  });
});
```

So my understanding is that you should use:
```javascript
var Reporter = require('jasmine-terminal-reporter');
var reporter = new Reporter({isVerbose: true});
jasmine.getEnv().addReporter(myReporter);

describe([...]
```

Does that help?

**Comment by jyoungqu** [comment]
That did the trick!
